#!/bin/dash

shrug-reset
touch a b c d
shrug-add a b
shrug-commit -m "added a b"

shrug-branch b1
shrug-checkout b1
# touch c d
rm b
shrug-add b c d
shrug-status

# shrug-commit -m "removed b and added c d"
# shrug-status

# shrug-checkout master
# shrug-status

# shrug-checkout b1
# shrug-status
