#!/bin/dash

shrug-reset
rm *
touch a b
shrug-add *
shrug-commit -m "added ab"
shrug-branch b1

seq 1 2 > a
echo 1 > b
shrug-add a b 
shrug-commit -m "12 in a, 1 in b"

shrug-checkout b1
seq 1 3 > a
shrug-add a
shrug-commit -m "123 in a"

shrug-checkout master
shrug-merge b1 -m "merging" 

