#!/bin/dash

shrug-reset
seq 1 7 > a
shrug-add a
shrug-commit -m "added a"

shrug-branch b1

seq 1 7 | sed 's/2/42/g' > a
shrug-add a
shrug-commit -m "changed a line 2"
cat a

shrug-checkout b1
seq 1 7 | sed 's/6/24/g' > a
shrug-add a
shrug-commit -m "changed a line 6"
cat a

shrug-checkout master
shrug-merge b1 -m "Merging"


