#!/bin/dash

2041-shrug-reset
touch a b c
2041 shrug-add a b c
2041 shrug-commit -m "Added a b c"

2041 shrug-branch b1
2041 shrug-checkout b1
echo b content > b
rm c
2041 shrug-add b c 
2041 shrug-commit -m "Removed c. Now a b"

2041 shrug-checkout master
echo c content > c
rm b
2041 shrug-add b
2041 shrug-commit -m "Removed b. Now a c"


