#!/bin/dash

shrug-reset
shrug-init
seq 1 7 >7.txt
shrug-add 7.txt
shrug-commit -m commit-0
shrug-branch b1
shrug-checkout b1
perl -pi -e s/2/42/ 7.txt
shrug-commit -a -m commit-1
shrug-checkout master
perl -pi -e s/5/24/ 7.txt
shrug-commit -a -m commit-2
shrug-merge b1 -m merge-message
shrug-log
shrug-status
