#!/bin/dash

shrug-reset
echo 1 > a

shrug-add a
shrug-commit -m "added a"
shrug-branch b1

shrug-checkout b1
rm a
shrug-add a
shrug-commit -m "removed a"

shrug-checkout master

shrug-status

echo world >> a
shrug-checkout b1 # Should result in changes being overwritten warning

# shrug-add b
# shrug-checkout b1 # Should still result in warning
# shrug-commit -m "committed changes"
# shrug-checkout b1 # Should be fine now

# shrug-wipe

# echo "===== REFERENCE ====="

# 2041-shrug-reset
# echo 1 > a

# 2041 shrug-add a
# 2041 shrug-commit -m "added a"
# 2041 shrug-branch b1

# 2041 shrug-checkout b1
# rm a
# 2041 shrug-add a
# 2041 shrug-commit -m "removed a"

# 2041 shrug-checkout master

# 2041 shrug-status

# echo world >> a
# 2041 shrug-checkout b1 # Should result in changes being overwritten warning

# 2041 shrug-add a
# 2041 shrug-checkout b1 # Should still result in warning

# 2041 shrug-commit -m "hello world in a"
# 2041 shrug-checkout b1 # Should proceed fine


