#!/bin/dash

# Initialises variables used in this script
. gitlite-conf
# Checks if the repo exists
. gitlite-exists

latestBranchCommit=$(gitlite-log | head -1 | cut -d' ' -f1)
headDir="$repoName/$latestBranchCommit"

# Check if the repository has any commits
if ! gitlite-get-head > /dev/null; then
    echo "$thisFile: error: your repository does not have any commits yet"
    exit 1
fi

stageFiles=$(ls $stageDir)
cwdFiles=$(ls)
headFiles=$(ls $headDir)

for eachFile in $(echo $stageFiles $cwdFiles $headFiles | tr " " "\n" | sort | uniq | tr "\n" " "); do
    stageFile="$stageDir/$eachFile"
    headFile="$headDir/$eachFile"
    currFile="$eachFile"
    # TODO: catch invalid filenames

    # Cases where the current file exists in CWD, stage and head:
    if test -e "$currFile" && test -e "$stageFile" && test -e "$headFile"; then
        if test -z "$(diff $currFile $stageFile)"; then
            # CWD file is identical to the stage file
            if test -z "$(diff $stageFile $headFile)"; then
                # Stage file is identical to the head file
                echo "$eachFile - same as repo"
            else 
                echo "$eachFile - file changed, changes staged for commit"
            fi
        else
            # CWD file is different to the stage file
            if test -z "$(diff $stageFile $headFile)"; then
                # Stage file is identical to the head file
                echo "$eachFile - file changed, changes not staged for commit"
            else 
                echo "$eachFile - file changed, different changes staged for commit"
            fi
        fi
    fi

    # One file missing from either CWD, stage or head
    if test -e "$currFile" && test -e "$stageFile" && ! test -e "$headFile"; then
        if test -z "$(diff $currFile $stageFile)"; then
            echo "$eachFile - added to index"
        else
            echo "$eachFile - added to index, file changed"
        fi
    fi

    if test -e "$currFile" && ! test -e "$stageFile" && test -e "$headFile"; then
        echo "$eachFile - untracked"
    fi

    if ! test -e "$currFile" && test -e "$stageFile" && test -e "$headFile"; then
        echo "$eachFile - file deleted"
    fi

    # Two files missing from CWD, stage or head
    if test -e "$currFile" && ! test -e "$stageFile" && ! test -e "$headFile"; then
        echo "$eachFile - untracked"
    fi

    if ! test -e "$currFile" && test -e "$stageFile" && ! test -e "$headFile"; then
        echo "$eachFile - added to index, file deleted"
    fi

    if ! test -e "$currFile" && ! test -e "$stageFile" && test -e "$headFile"; then
        echo "$eachFile - deleted"
    fi
done
