#!/bin/dash
# Creates the repo, an empty master branch and an empty index

# Initialises variables used in this script
. gitlite-conf

# Creating the repo subdirectory
if mkdir "$repoName" 2> /dev/null; then
    # Creating the index directory if it doesn't exist
    if ! test -e "$stageDir"; then
        mkdir "$stageDir"
    fi
    # Creating an empty master branch under the repo subdirectory 
    # and set it as the current branch (by symlink)
    masterBranch="$repoName/$master"
    mkdir "$masterBranch"
    cd "$repoName"
    ln -sfn "$master" "$currBranch"
    cd ..
    echo "Initialized empty gitlite repository in .gitlite"
else 
    echo "$thisFile: error: $repoName already exists"
fi
