#!/bin/dash
# Stages the target files in the repo index

# Initialises variables used in this script
. gitlite-conf
# Checks if the repo exists
. gitlite-exists

# First check if all the supplied filenames exist in the current directory or index
for eachFile in "$@"; do
    if ! test -e "$eachFile"; then
        if ! test -e "$stageDir/$eachFile"; then
            echo "$thisFile: error: can not open '$eachFile'"
            exit 1
        else
            continue
        fi
    fi
done

for eachFile in "$@"; do
    if test -e "$eachFile"; then
        # Target file already exists - ie. it was staged already
        # cp overwrites the existing staged file by default
        cp "$eachFile" "$stageDir"
    else
        # Target file does not exist in the current directory.
        if test -e "$stageDir/$eachFile"; then  
            # If it exists in the index however, then it was probably from the cwd
            # Proceed to remove the target from the index
            rm "$stageDir/$eachFile"
        else 
            if ! gitlite-validname "$eachFile"; then
                # Check that the filename is valid
                echo "$thisFile: error: invalid filename '$eachFile'"
                exit 1
            else 
                echo "$thisFile: error: can not open '$eachFile'"
                exit 1
            fi
        fi
    fi
done
