#!/bin/dash

# Initialises variables used in this script
. gitlite-conf
# Checks if the repo exists
. gitlite-exists

# Incorrect usage
if test "$#" -ne 1; then
  echo "usage: $thisFile <commit>:<filename>"
  exit 1
fi

commitNum=$(echo $1 | cut -d':' -f1 -s)
fileToShow=$(echo $1 | cut -d':' -f2 -s)

if test -z "$commitNum" && test -z "$fileToShow"; then
	# No colon inside the supplied argument
	echo "$thisFile: error: invalid object $1"	
	exit 1
elif ! gitlite-validname "$fileToShow" 2> /dev/null; then
	echo "$thisFile: error: invalid filename '$fileToShow'"
	exit 1
fi

commitDir=""
if test -z "$commitNum"; then
	# No commit number/hash specified. Showing file from the index
	commitDir="$stageDir"
	if ! test -e "$stageDir/$fileToShow"; then
		# File to show doesn't exist in the index
		echo "$thisFile: error: '$fileToShow' not found in $stage"
		exit 1
	fi
else 
	commitDir="$repoName/$commitNum"
	if ! test -e "$commitDir"; then
		# Specified commit doesn't exist
		echo "$thisFile: error: unknown commit '$commitNum'"
		exit 1 
	fi
	if ! test -e "$commitDir/$fileToShow"; then
		echo "$thisFile: error: '$fileToShow' not found in commit $commitNum"
		exit 1
	fi
fi

cat "$commitDir/$fileToShow"
