#!/bin/dash
# Exits with status 0 if the supplied name IS valid
# Exits with status 1 if the supplied name is NOT valid

if test -z $(echo "$1" | egrep "^[a-zA-Z0-9]+[-._a-zA-Z0-9]*$") > /dev/null; then
    exit 1
else 
    exit 0
fi
