#!/bin/dash

# Initialises variables used in this script
. shrug-conf
# Checks if the repo exists
. shrug-exists

branchName=$1
branchDir="$repoName/$branchName"
latestBranchCommit=$(shrug-log | head -1 | cut -d' ' -f1)
headFile="$repoName/$latestBranchCommit/$targetFile"

cd "$repoName"

if test "$(readlink $currBranch)" = $branchName; then
    # If current-branch is already pointing to the target branch, do nothing
    echo "Already on '$branchName'"
    exit 0
else
    # If the branch doesn't exist, we can't checkout to it
    if ! test -e $branchName; then
        echo "$thisFile: error: unknown branch '$branchName'"
        exit 1
    fi
    # TODO: User needs to commit their changes before checking out

    stageFiles=$(ls $stage)
    cwdFiles=$(ls ../)
    branchFiles=$(ls $branchName)

    cd ..

    willOverwrite=false
    for eachFile in $(echo $stageFiles $cwdFiles $branchFiles | tr " " "\n" | sort | uniq | tr "\n" " "); do
        cwdFile="$eachFile"
        branchFile="$repoName/$branchName/$eachFile"
        stageFile="$stageDir/$eachFile"
        headFile="$headDir/$eachFile"

        # If the file exists in target branch AND cwd BUT NOT in index, then
        # replacing this file would overwrite uncommitted changes
        if test -e "$branchFile" && test -e "$cwdFile" && ! test -e "$stageFile"; then
            if test $willOverwrite = "false"; then
                echo "$thisFile: error: Your changes to the following files would be overwritten by checkout:"
                willOverwrite=true
            fi
            echo "$eachFile"
        fi

        # If the file doesn't exist in the target branch, checkout may deleted uncommitted
        # work in the CWD file with the same name
        if ! test -e "$branchFile" ; then
            if shrug-file-intersects "$eachFile" > /dev/null; then
                if test $willOverwrite = "false"; then
                    echo "$thisFile: error: Your changes to the following files would be overwritten by checkout:"
                    willOverwrite=true
                fi
                echo "$eachFile"
            fi
        fi
    done
    if test $willOverwrite = "true"; then
        exit 1
    fi

    # For each file in either the stage, cwd or target branch
    for eachFile in $(echo $stageFiles $cwdFiles $branchFiles | tr " " "\n" | sort | uniq | tr "\n" " "); do
        if test -e "$repoName/$branchName/$eachFile"; then
            if ! shrug-file-should-commit $eachFile > /dev/null; then
                rm "$eachFile" 2> /dev/null
                rm "$stageDir/$eachFile" 2> /dev/null
                cp "$repoName/$branchName/$eachFile" "$eachFile"
                cp "$repoName/$branchName/$eachFile" "$stageDir/$eachFile"
            fi  
        else
            if ! shrug-file-should-commit $eachFile > /dev/null; then
                rm "$eachFile" 2> /dev/null
                rm "$stageDir/$eachFile" 2> /dev/null
            fi  
        fi
    done
    cd "$repoName"
    ln -sfn "$branchName" "$currBranch"
    echo "Switched to branch '$branchName'"
fi
