#!/bin/dash

thisFilename=$(basename "$0")
repoName=".shrug"
master="master"

if mkdir "$repoName" 2> /dev/null; then
    # Creating a master branch
    masterBranch="$repoName/$master"
    mkdir "$masterBranch"
    # TODO: Push everything in cwd to master branch?
    cp $(ls) $masterBranch 2> /dev/null  # TODO: Add -r?
    echo "Initialized empty shrug repository in .shrug"
else 
    echo "$thisFilename: error: $repoName already exists"
fi
