#!/bin/dash

while test $# -gt 0; do  # $# is the number of args
    case "$1" in
        -a) 
            echo "Adding all files"
            shift
            ;;
        -m)
            # Extract the commit message
            shift
            message=$1
            shift
            ;;
        *)
            echo usage: shrug-commit [-a] -m commit-message
            exit 1
            ;;
    esac
done

# Variables:
repoName=".shrug"
stageDir="$repoName/index"
commitNum=0
commitDir="$repoName/$commitNum"
logFile="$repoName/.log"

while test -e "$commitDir"; do
    commitNum=$(expr $commitNum + 1)
    commitDir="$repoName/$commitNum"
done

# Creating a snapshot folder
mkdir "$commitDir" || exit 1

# Check if the index/staging area is empty (NOT ROBUST?)
if test -z "$(ls "${stageDir}")"; then
    echo "nothing to commit"
    exit 1
fi

# For each file in the index/staging area, copy each into the snapshot folder
for eachFile in $(ls "${stageDir}"); do
    # echo " ===> Committing $eachFile"
    cp "${stageDir}/$eachFile" "$commitDir"
done

# Writing to the log file
logMessage="$commitNum ${message}"
if ! test -e "$logFile"; then
    echo "$logMessage" > "$logFile"
else
    sed -i.old "1s;^;$commitNum ${message}\n;" "$logFile"
fi

echo "Committed as commit $commitNum"
