#!/bin/dash
# Stages the target files in the repo index

# Initialises variables used in this script
. shrug-conf
# Checks if the repo exists
. shrug-exists

for eachFile in "$@"; do
    if test -e "$eachFile"; then
        # Target file already exists - ie. it was staged already
        # cp overwrites the existing staged file by default
        cp "$eachFile" "$stageDir"
    else
        # Target file does not exist in the current directory.
        if test -e "$stageDir/$eachFile"; then  
            # If it exists in the index however, then it was probably from the cwd
            # Proceed to remove the target from the index
            rm "$stageDir/$eachFile"
        else 
            if ! sh shrug-validname "$eachFile"; then
                # Check that the filename is valid
                echo "$thisFile: error: invalid filename '$eachFile'"
                exit 1
            else 
                echo "$thisFile: error: can not open '$eachFile'"
                exit 1
            fi
        fi
    fi
done
