#!/bin/dash

. shrug-conf
cwd=$(pwd)

# Check if the repository has any commits
if ! sh get-head > /dev/null; then
    echo "$thisFile: error: your repository does not have any commits yet"
    exit 1
fi

stageFiles=$(ls $stageDir)
cwdFiles=$(ls $cwd)
headFiles=$(ls $headDir)

for eachFile in $(echo $stageFiles $cwdFiles $headFiles | tr " " "\n" | sort | uniq | tr "\n" " "); do
    stageFile="$stageDir/$eachFile"
    headFile="$headDir/$eachFile"
    currFile="$cwd/$eachFile"
    # TODO: catch invalid filenames

    # All files exist
    if test -e "$currFile" && test -e "$stageFile" && test -e "$headFile"; then
        if test -z "$(diff $currFile $stageFile)"; then
            if test -z "$(diff $stageFile $headFile)"; then
                echo "$eachFile - same as repo"
            else 
                echo "$eachFile - file changed, changes staged for commit"
            fi
        else
            if test -z "$(diff $stageFile $headFile)"; then
                echo "$eachFile - file changed, changes not staged for commit"
            else 
                echo "$eachFile - file changed, different changes staged for commit"
            fi
        fi
    fi

    # One file missing
    if test -e "$currFile" && test -e "$stageFile" && ! test -e "$headFile"; then
        if test -z "$(diff $currFile $stageFile)"; then
            echo "$eachFile - added to index"
        else
            echo "$eachFile - added to index, file changed"
        fi
    fi

    if test -e "$currFile" && ! test -e "$stageFile" && test -e "$headFile"; then
        echo "$eachFile - untracked"
    fi

    if ! test -e "$currFile" && test -e "$stageFile" && test -e "$headFile"; then
        echo "$eachFile - file deleted"
    fi

    # Two files missing
    if test -e "$currFile" && ! test -e "$stageFile" && ! test -e "$headFile"; then
        echo "$eachFile - untracked"
    fi

    if ! test -e "$currFile" && test -e "$stageFile" && ! test -e "$headFile"; then
        echo "$eachFile - added to index, file deleted"
    fi

    if ! test -e "$currFile" && ! test -e "$stageFile" && test -e "$headFile"; then
        echo "$eachFile - deleted"
    fi
done
