#!/bin/dash

# Variables:
repoName=".shrug"
stageDir="$repoName/index"
commitNum=0
commitDir="$repoName/$commitNum"
logFile="$repoName/.log"

# Check if the repo exists
if ! test -e "$repoName"; then
    echo "$0: error: no .shrug directory containing shrug repository exists"
    exit 1
fi

# Creating the index directory if it doesn't exist (should this be done?)
if ! test -e "$stageDir"; then
    mkdir "$stageDir"
    echo "nothing to commit"
    exit 1
fi

while test $# -gt 0; do  # $# is the number of args
    case "$1" in
        -a) 
            for eachFile in $(ls "$stageDir"); do
                # echo "!!! Fetching $eachFile from current directory"
                # If the file has been deleted, then also remove from the index
                if test -e "./$eachFile"; then
                    # echo "Found here!"
                    cp "./$eachFile" "$stageDir/$eachFile"
                else
                    # echo " ===> File has been deleted"
                    rm "$stageDir/$eachFile"
                fi

            done
            # dash shrug-add 
            shift
            ;;
        -m)
            # Extract the commit message
            shift
            message=$1
            if test -z "$message"; then
                echo "usage: $0 [-a] -m commit-message"
                exit 1
            fi
            shift
            ;;
        *)
            echo "usage: $0 [-a] -m commit-message"
            exit 1
            ;;
    esac
done

# Check if the index/staging area is empty (Should I do this? NOT ROBUST either?)
# if test -z "$(ls "${stageDir}")"; then
#     echo "nothing to commit"
#     exit 1
# fi

# Check if the stage contains additional files/modifications that need to be
# committed to a new snapshot by comparing with the latest commit
if ! sh should-commit > /dev/null; then
    echo "nothing to commit"
    exit 1
fi

while test -e "$commitDir"; do
    commitNum=$(expr $commitNum + 1)
    commitDir="$repoName/$commitNum"
done

# Creating a snapshot folder
mkdir "$commitDir" || exit 1

# For each file in the index/staging area, copy each into the snapshot folder
for eachFile in $(ls "${stageDir}"); do
    # echo " ===> Committing $eachFile"
    cp "${stageDir}/$eachFile" "$commitDir"
done

# Writing to the log file
logMessage="$commitNum ${message}"
if ! test -e "$logFile"; then
    echo "$logMessage" > "$logFile"
else
    sed -i.old "1s;^;$commitNum ${message}\n;" "$logFile"
fi

echo "Committed as commit $commitNum"
