#!/bin/dash

repoName=".shrug"
logFile="$repoName/.log"

# Check if the repo exists
if ! test -e "$repoName"; then
    echo "$0: error: no .shrug directory containing shrug repository exists"
    exit 1
fi

if ! test -e "$logFile"; then
    echo "$0: error: your repository does not have any commits yet"
    exit 1
fi

cat "$logFile"
