#!/bin/dash

. shrug-conf
. shrug-exists

message=""
while test $# -gt 0; do  # $# is the number of args
    case "$1" in
        -a) 
            for eachFile in $(ls "$stageDir"); do
                if test -e "./$eachFile"; then
                    cp "./$eachFile" "$stageDir/$eachFile"
                else
                    # If the current file has been deleted in the cwd, then also remove it from the index
                    rm "$stageDir/$eachFile"
                fi
            done
            shift
            ;;
        -m)
            # Extracting the commit message
            shift
            message=$1
            if test -z "$message"; then
                echo "usage: $thisFile [-a] -m commit-message"
                exit 1
            fi
            shift
            ;;
        *)
            echo "usage: $thisFile [-a] -m commit-message"
            exit 1
            ;;
    esac
done

# Checks if the commit should proceed or if there's 'nothing to commit'
# TODO: Alternative to sh? Why does dash not work?
if ! sh shrug-should-commit > /dev/null; then
    echo "nothing to commit"
    exit 1
fi

# Get new commit number
while test -e "$commitDir"; do
    commitNum=$(expr $commitNum + 1)
    commitDir="$repoName/$commitNum"
done

# Creating a snapshot folder
mkdir "$commitDir" || exit 1


# First remove everything in the current branch
cd $repoName/$currBranch
rm $(ls) 2> /dev/null
cd ../..

# For each file in the index/staging area, copy each into the snapshot folder
for eachFile in $(ls "${stageDir}"); do
    cp "${stageDir}/${eachFile}" "$commitDir"
    # Also copy to the current branch subdirectory (so that it contains the latest commit)
    cp "${stageDir}/${eachFile}" "${repoName}/${currBranch}/${eachFile}"  
done

# Writing to the log file
logMessage="$commitNum ${message}"
if ! test -e "$logFile"; then
    echo "$logMessage" > "$logFile"
else
    # Prepends the log message to the current branch's log file
    sed -i.old "1s;^;$commitNum ${message}\n;" "$logFile"
fi

echo "Committed as commit $commitNum"
