#!/bin/dash
# Check if the stage contains additional files/modifications that need to be
# committed to a new snapshot by comparing with the latest commit.
# Exits with status 0 if there are additional files/modifications in the stage that
# are currently not in the latest head directory.
# Otherwise exit with status 1 if there is nothing to commit

# Initialises variables used in this script
. shrug-conf
# Checks if the repo exists
. shrug-exists

latestBranchCommit=$(shrug-log | head -1 | cut -d' ' -f1)
headDir="$repoName/$latestBranchCommit"

# For each file in the stage, check if it is in the head commit. If it is,
# then additionally check whether there is a difference. 
for eachFile in $(ls $stageDir); do
    stageFile="$stageDir/$eachFile"
    latestBranchCommit=$(shrug-log | head -1 | cut -d' ' -f1)
    headFile="$repoName/$latestBranchCommit/$targetFile"
    echo "Comparing: $stageFile and $headFile"
    
    if test -e "$headFile"; then
        # If the file exists in both the head AND stage, check if they are identical
        echo " ===> File exists in the head directory"
        if diff $headFile $stageFile > /dev/null 2> /dev/null && test -z "$(diff $headFile $stageFile)"; then
            echo " ===> Files are identical!"
        else 
            # Stage has a file that's been modified. The commit should proceed
            echo " ===> File modified. Commit can proceed"
            exit 0
        fi
    else
        # The stage has a file which is NOT IN the head. The commit should proceed
        echo " ===> File in stage does not exist in head. Commit can proceed"
        exit 0
    fi
done

for eachFile in $(ls $headDir); do
    stageFile="$stageDir/$eachFile"
    latestBranchCommit=$(shrug-log | head -1 | cut -d' ' -f1)
    headFile="$repoName/$latestBranchCommit/$targetFile"
    
    echo "Comparing: $stageFile and $headFile"
    if ! test -e "$stageFile"; then
        # The head commit has a file which is not in the stage. This means the commit should proceed
        echo " ===> File in HEAD does not exist in stage. A file must have been removed. Commit can proceed"
        exit 0
    fi
done

echo "Nothing to commit"
exit 1
