#!/bin/dash

# Variables
repoName=".shrug"
stageDir="index"

# Check if the repo exists
if ! test -e "$repoName"; then
    echo "$0: error: no .shrug directory containing shrug repository exists"
    exit 1
fi


# No commits in the repo
if ! sh get-head > /dev/null; then
	echo "$0: error: your repository does not have any commits yet"
	exit 1
fi

# Incorrect usage
if test "$#" -ne 1; then
  echo "usage: $0 <commit>:<filename>"
  exit 1
fi

commitNum=$(echo $1 | cut -d':' -f1 -s)
fileToShow=$(echo $1 | cut -d':' -f2 -s)

if test -z "$commitNum" && test -z "$fileToShow"; then
	# No colon inside the supplied argument
	echo "$0: error: invalid object $1"	
	exit 1
elif ! sh validname "$fileToShow"; then
	echo "$0: error: invalid filename '$fileToShow'"
	exit 1
fi

commitDir=""
if test -z "$commitNum"; then
	# No commit number/hash specified. Using index
	commitDir="$repoName/$stageDir"
	if ! test -e "$commitDir/$fileToShow"; then
		echo "$0: error: '$fileToShow' not found in $stageDir"
		exit 1
	fi
else 
	commitDir="$repoName/$commitNum"
	if ! test -e "$commitDir"; then
		echo "$0: error: unknown commit '$commitNum'"
		exit 1 
	fi

	if ! test -e "$commitDir/$fileToShow"; then
		echo "$0: error: '$fileToShow' not found in commit $commitNum"
		exit 1
	fi
fi

cat "$commitDir/$fileToShow"
