#!/bin/dash

# # Case 1:
# echo "===== CASE 1 ====="
# shrug-reset-hard

# echo 1 > a

# 2041 shrug-add a
# 2041 shrug-commit -m "added a"

# 2041 shrug-branch b1

# echo 2 >> a
# 2041 shrug-add a

# echo 3 >> a
# 2041 shrug-status  # a - file changed, different changes staged for commit

# 2041 shrug-checkout b1
# 2041 shrug-status  # a - file changed, different changes staged for commit (didn't swap out the file)

# # Case 2:
# echo "===== CASE 2 ====="
# shrug-reset-hard

# echo 1 > a
# 2041 shrug-add a
# 2041 shrug-commit -m "Added a"

# 2041 shrug-branch b1

# echo 2 >> a
# 2041 shrug-add a
# 2041 shrug-status  # a - file changed, changes staged for commit

# 2041 shrug-checkout b1
# 2041 shrug-status  # a - file changed, changes staged for commit (didn't swap out the file)

# # Case 3:
# echo "===== CASE 3 ====="
# shrug-reset-hard

# echo 1 > a
# 2041 shrug-add a
# 2041 shrug-commit -m "Added a"

# 2041 shrug-branch b1

# echo 2 >> a
# 2041 shrug-add a

# echo 1 > a
# 2041 shrug-status 

# 2041 shrug-checkout b1
# 2041 shrug-status  # a - file changed, different changes staged for commit (didn't swap out the file)

# # Case 4:
# echo "===== CASE 4 ====="
# shrug-reset-hard

# echo 1 > a
# 2041 shrug-add a
# 2041 shrug-commit -m "Added a"

# 2041 shrug-branch b1

# echo 2 >> a

# 2041 shrug-status  # a - file changed, changes not staged for commit

# 2041 shrug-checkout b1
# 2041 shrug-status  # a - file changed, changes not staged for commit (didn't swap out the file)

# Case 5
echo "===== CASE 5 ====="
shrug-reset-hard

echo 1 > a
echo 1 > b
2041 shrug-add a b
2041 shrug-commit -m "Added a and b"

2041 shrug-branch b1
2041 shrug-checkout b1

rm a
2041 shrug-add a
2041 shrug-commit -m "Removed a in b1"
2041 shrug-status  # ONLY HAS b and not a

2041 shrug-checkout master
2041 shrug-status  # Shows a AND b

2041 shrug-checkout b1
2041 shrug-status  # Shows only b

# Case 6
echo "===== CASE 6 ====="
shrug-reset-hard

echo 1 > a
echo 1 > b
2041 shrug-add a b
2041 shrug-commit -m "Added a and b"

2041 shrug-branch b1
2041 shrug-checkout b1

rm a
2041 shrug-add a
2041 shrug-commit -m "Removed a in b1"

2041 shrug-checkout master

echo 2 >> a
2041 shrug-add a

2041 shrug-checkout b1
2041 shrug-status


