#!/bin/dash
# Initialises variables used by other shrug scripts

# Strips the leading path up to the last forward slash /
thisFile=$(basename "$0")

repoName=".shrug"
master="master"
currBranch="current-branch"
stage="index"
stageDir="$repoName/$stage"
logFile="$repoName/$currBranch/.log"

commitNum=0
commitDir="$repoName/$commitNum"
latestCommit=$(shrug-get-head)
headDir="$repoName/$latestCommit"
